{"name": "test_update_database_validation_error", "status": "passed", "description": "Verify that updating a database returns expected results", "attachments": [{"name": "log", "source": "a0f20745-2a01-4134-a4d2-7b09b1e6ae82-attachment.txt", "type": "text/plain"}], "start": 1718901412044, "stop": 1718901412558, "uuid": "3c8167fc-1b76-4b8f-9038-2e3dc19418c0", "historyId": "b5551348997949019d3be766e39f0bc5", "testCaseId": "b5551348997949019d3be766e39f0bc5", "fullName": "test_update_database#test_update_database_validation_error", "labels": [{"name": "parentSuite", "value": "databases"}, {"name": "severity", "value": "allure.severity_level.CRITICAL"}, {"name": "feature", "value": "databases"}, {"name": "suite", "value": "schemabased"}, {"name": "tag", "value": "schemabased"}, {"name": "host", "value": "Noutbuk-Dmitrij.local"}, {"name": "thread", "value": "27260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_update_database"}]}